config/routes.rb
Poetas::Application.routes.draw do

  #devise_for must be the first route for Heroku prod
  # rescue on migrate:
  # http://code-n-fold.com/2012/04/21/rails-3-1-devise_for-breaks-dbmigrate-fix-6/
  begin
    devise_for(:users)
  rescue Exception => e
    puts "Devise error: #{e.class}: #{e}"
  end

  root(to: "static_pages#home")

  resource(:admin, controller: 'admin')

  namespace(:admin) do
    resources(:users) do
      member do
        get('revive')
      end
    end
  end

  resources(:poems) do
    member { post :vote }
  end

  resources(:poets, controller: "users") do
    resources :poems
  end

  match('/profile', to: "users#profile")
  match('/contact', to: 'static_pages#contact')
  match('/about',   to: 'static_pages#about')

  devise_scope(:user) do
    match('/signup', to: 'devise/registrations#new')
    match('/signin', to: 'devise/sessions#new')
    match('/logout', to: 'devise/sessions#destroy')
  end

end
#== Route Map
# Generated on 11 Dec 2012 06:43
#
#             user_session POST   /users/sign_in(.:format)                 devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                devise/sessions#destroy
# cancel_user_registration GET    /users/cancel(.:format)                  devise/registrations#cancel
#        user_registration POST   /users(.:format)                         devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                 devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                    devise/registrations#edit
#                          PUT    /users(.:format)                         devise/registrations#update
#                          DELETE /users(.:format)                         devise/registrations#destroy
#                     root        /                                        static_pages#home
#                    admin POST   /admin(.:format)                         admin#create
#                new_admin GET    /admin/new(.:format)                     admin#new
#               edit_admin GET    /admin/edit(.:format)                    admin#edit
#                          GET    /admin(.:format)                         admin#show
#                          PUT    /admin(.:format)                         admin#update
#                          DELETE /admin(.:format)                         admin#destroy
#        revive_admin_user GET    /admin/users/:id/revive(.:format)        admin/users#revive
#              admin_users GET    /admin/users(.:format)                   admin/users#index
#                          POST   /admin/users(.:format)                   admin/users#create
#           new_admin_user GET    /admin/users/new(.:format)               admin/users#new
#          edit_admin_user GET    /admin/users/:id/edit(.:format)          admin/users#edit
#               admin_user GET    /admin/users/:id(.:format)               admin/users#show
#                          PUT    /admin/users/:id(.:format)               admin/users#update
#                          DELETE /admin/users/:id(.:format)               admin/users#destroy
#                    poems GET    /poems(.:format)                         poems#index
#                          POST   /poems(.:format)                         poems#create
#                 new_poem GET    /poems/new(.:format)                     poems#new
#                edit_poem GET    /poems/:id/edit(.:format)                poems#edit
#                     poem GET    /poems/:id(.:format)                     poems#show
#                          PUT    /poems/:id(.:format)                     poems#update
#                          DELETE /poems/:id(.:format)                     poems#destroy
#               poet_poems GET    /poets/:poet_id/poems(.:format)          poems#index
#                          POST   /poets/:poet_id/poems(.:format)          poems#create
#            new_poet_poem GET    /poets/:poet_id/poems/new(.:format)      poems#new
#           edit_poet_poem GET    /poets/:poet_id/poems/:id/edit(.:format) poems#edit
#                poet_poem GET    /poets/:poet_id/poems/:id(.:format)      poems#show
#                          PUT    /poets/:poet_id/poems/:id(.:format)      poems#update
#                          DELETE /poets/:poet_id/poems/:id(.:format)      poems#destroy
#                    poets GET    /poets(.:format)                         users#index
#                          POST   /poets(.:format)                         users#create
#                 new_poet GET    /poets/new(.:format)                     users#new
#                edit_poet GET    /poets/:id/edit(.:format)                users#edit
#                     poet GET    /poets/:id(.:format)                     users#show
#                          PUT    /poets/:id(.:format)                     users#update
#                          DELETE /poets/:id(.:format)                     users#destroy
#                  profile        /profile(.:format)                       users#profile
#                  contact        /contact(.:format)                       static_pages#contact
#                    about        /about(.:format)                         static_pages#about
#                   signup        /signup(.:format)                        devise/registrations#new
#                   signin        /signin(.:format)                        devise/sessions#new
#                   logout        /logout(.:format)                        devise/sessions#destroy

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :authenticate_user!, except: [:home, :about, :contact]

  def home
    @poems_count = Poem.count
    @poets_count = User.count
    @latest_poet = User.last
    @featured_poem = Poem.last
  end

  def about
  end

  def contact
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def full_title(title)
    base_title = "Poetas"
    if title.empty?
      base_title 
    else
      "#{base_title} - #{title}"
    end
  end
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
<div>
  <h1>Welcome!</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  <h2>Community news</h2>
  <p>Poetas welcomes our lastest poet <strong><%= @latest_poet.name %></strong> . Our community has grown to <%= pluralize(@poets_count, 'poets') %>! And 
    so far we have <%= pluralize(@poems_count, 'poem') %> added to the site!</p><br><br>
  <h2>Featured Poem</h2>
  <h3> <%= @featured_poem.try(:title) %></h3>
  <p> <%= @featured_poem.try(:body) %></p>
  <p> by <%= @featured_poem.try(:user).try(:name) %>.</p>
</div>

<% else %>

<div class="center hero-unit">
  <h1>Welcome to the Poetas site!</h1>

  <h2>
    Poetas is the new hub for aspiring poets and writers. Sign up and share your poetry and short stories with us!
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %> <b>or</b>
  <%= link_to "Sign in!", signin_path, class: "btn btn-large btn-primary" %> 

</div>
<% end %>

app/views/static_pages/profile.html.erb
<% provide(:title, 'Profile') %>
<h1><%= @user.name %>&#39;s Profile</h1>
<div class="row">
  <div class="span6  offset3">
    <ul>
      <li><b>Email:</b> <%= current_user.email %> </li>
      <li><b>Account created on:</b> <%= current_user.created_at %> </li>
      <li><b>Account updated at:</b> <%= current_user.updated_at %> </li>
      <li><b>Account last sign in at:</b> <%= current_user.last_sign_in_at %> </li>
      <li><b>Account last sign in ip:</b> <%= current_user.current_sign_in_ip %> </li>
    </ul>
  </div>
</div>