config/routes.rb
Poetas::Application.routes.draw do

  #devise_for must be the first route for Heroku prod
  # rescue on migrate:
  # http://code-n-fold.com/2012/04/21/rails-3-1-devise_for-breaks-dbmigrate-fix-6/
  begin
    devise_for(:users)
  rescue Exception => e
    puts "Devise error: #{e.class}: #{e}"
  end

  root(to: "static_pages#home")

  resource(:admin, controller: 'admin')

  namespace(:admin) do
    resources(:users) do
      member do
        get('revive')
      end
    end
  end

  resources(:poems) do
    member { post :vote }
  end

  resources(:poets, controller: "users") do
    resources :poems
  end

  match('/profile', to: "users#profile")
  match('/contact', to: 'static_pages#contact')
  match('/about',   to: 'static_pages#about')

  devise_scope(:user) do
    match('/signup', to: 'devise/registrations#new')
    match('/signin', to: 'devise/sessions#new')
    match('/logout', to: 'devise/sessions#destroy')
  end

end
#== Route Map
# Generated on 11 Dec 2012 06:43
#
#             user_session POST   /users/sign_in(.:format)                 devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                devise/sessions#destroy
# cancel_user_registration GET    /users/cancel(.:format)                  devise/registrations#cancel
#        user_registration POST   /users(.:format)                         devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                 devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                    devise/registrations#edit
#                          PUT    /users(.:format)                         devise/registrations#update
#                          DELETE /users(.:format)                         devise/registrations#destroy
#                     root        /                                        static_pages#home
#                    admin POST   /admin(.:format)                         admin#create
#                new_admin GET    /admin/new(.:format)                     admin#new
#               edit_admin GET    /admin/edit(.:format)                    admin#edit
#                          GET    /admin(.:format)                         admin#show
#                          PUT    /admin(.:format)                         admin#update
#                          DELETE /admin(.:format)                         admin#destroy
#        revive_admin_user GET    /admin/users/:id/revive(.:format)        admin/users#revive
#              admin_users GET    /admin/users(.:format)                   admin/users#index
#                          POST   /admin/users(.:format)                   admin/users#create
#           new_admin_user GET    /admin/users/new(.:format)               admin/users#new
#          edit_admin_user GET    /admin/users/:id/edit(.:format)          admin/users#edit
#               admin_user GET    /admin/users/:id(.:format)               admin/users#show
#                          PUT    /admin/users/:id(.:format)               admin/users#update
#                          DELETE /admin/users/:id(.:format)               admin/users#destroy
#                    poems GET    /poems(.:format)                         poems#index
#                          POST   /poems(.:format)                         poems#create
#                 new_poem GET    /poems/new(.:format)                     poems#new
#                edit_poem GET    /poems/:id/edit(.:format)                poems#edit
#                     poem GET    /poems/:id(.:format)                     poems#show
#                          PUT    /poems/:id(.:format)                     poems#update
#                          DELETE /poems/:id(.:format)                     poems#destroy
#               poet_poems GET    /poets/:poet_id/poems(.:format)          poems#index
#                          POST   /poets/:poet_id/poems(.:format)          poems#create
#            new_poet_poem GET    /poets/:poet_id/poems/new(.:format)      poems#new
#           edit_poet_poem GET    /poets/:poet_id/poems/:id/edit(.:format) poems#edit
#                poet_poem GET    /poets/:poet_id/poems/:id(.:format)      poems#show
#                          PUT    /poets/:poet_id/poems/:id(.:format)      poems#update
#                          DELETE /poets/:poet_id/poems/:id(.:format)      poems#destroy
#                    poets GET    /poets(.:format)                         users#index
#                          POST   /poets(.:format)                         users#create
#                 new_poet GET    /poets/new(.:format)                     users#new
#                edit_poet GET    /poets/:id/edit(.:format)                users#edit
#                     poet GET    /poets/:id(.:format)                     users#show
#                          PUT    /poets/:id(.:format)                     users#update
#                          DELETE /poets/:id(.:format)                     users#destroy
#                  profile        /profile(.:format)                       users#profile
#                  contact        /contact(.:format)                       static_pages#contact
#                    about        /about(.:format)                         static_pages#about
#                   signup        /signup(.:format)                        devise/registrations#new
#                   signin        /signin(.:format)                        devise/sessions#new
#                   logout        /logout(.:format)                        devise/sessions#destroy

app/models/poem.rb
# == Schema Information
#
# Table name: poems
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  body       :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  deleted_at :datetime
#

class Poem < ActiveRecord::Base
  attr_accessible :body, :title
  belongs_to :user
  validates :body, :title, :user_id, presence: true
  default_scope order: 'poems.created_at DESC'
  #reputions system
  has_reputation :votes, source: :user, aggregate_by: :sum
end

app/controllers/poems_controller.rb
include ActionView::Helpers::TextHelper
class PoemsController < ApplicationController

  def index
    @poet = params[:poet_id] ? User.find(params[:poet_id]) : current_user
    @poems = @poet.poems.page(params[:page]).per(10)
    @votes = @poems.find_with_reputation(:votes, :all, order: 'votes desc')
  end

  def new
    @poem = Poem.new
  end

  def show
    @poem = Poem.find(params[:id])
    #need to use simple_format here for the text_analyzer to work
    @poem_text = simple_format(@poem.body)
    @ta = Poetas::TextAnalyzer.new(@poem_text)
  end

  def create
    @poet = current_user
    @poem = @poet.poems.create(params[:poem])

    if @poem.save
      redirect_to(@poem, notice =>'Your poem was successfully created.')
    else
      render('new')
    end
  end

  def edit
    @poem = Poem.find(params[:id])
  end

  def update
    @poem = Poem.find(params[:id])

    if @poem.update_attributes(params[:poem])
      redirect_to(@poem, :notice => 'Your poem was successfully updated.')
    else
      render('edit')
    end
  end

  def destroy
    #make sure it's the correct user
    @poem = current_user.poems.find(params[:id])
    @poem.destroy
    redirect_to(poems_url)
  end

  #voting on poems
  def vote
    value = params[:type] == 'vote' ? 1 : 0;
    @poem = Poem.find(params[:id])
    @poem.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back, notice: "Thank you for voting!!"
  end

  private

end

app/helpers/poems_helper.rb
module PoemsHelper

end

app/views/poems/_form.html.erb
<%= form_for(@poem) do |f| %>
  <% if @poem.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@poem.errors.count, "error") %> prohibited
        this poem from being saved:</h2>
    <ul>
    <% @poem.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body, "Poem" %>
    <%= f.text_area :body, placeholder: "Compose new poem...", rows: "10" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/poems/_poem.html.erb
<li>
  <span class="title"><%= poem.title %></span>
  <span class="body"><%= truncate(poem.body, length: 80) %></span>
  <span class="timestamp">
    Created <%= time_ago_in_words(poem.created_at) %> ago. <br>
  </span>
  <span class="links">
    <%= link_to('Show Poem', poem_path(poem)) %>
      <% if current_user.id == @poet.id %>
      | <%= link_to('Delete Poem', poem,
                    method: :delete,
                    data: { confirm: "Are you sure?"},
                    title: poem.title) %>
      <% end %>
  </span>
</li>

app/views/poems/_text_analyzer.html.erb
  <br><br>
  <span class="analyzer">
  <h4>Poem Analysis for <%= @poem.title %></h4>
    <ul >
      <li><%= pluralize(@ta.lines_count, 'line') %> </li>
      <li><%= @ta.character_count %> characters</li>
      <li><%= @ta.character_count_nospaces %> characters (no spaces)</li>
      <li><%= pluralize(@ta.sentence_count, 'sentence') %></li>
      <li><%= pluralize(@ta.paragraph_count, 'paragraph') %> </li>
      <li><%= pluralize(@ta.words_per_sentence, 'word')  %> per sentence (average)</li>
      <li><%= pluralize(@ta.sentences_per_paragraph, 'sentence')  %> per paragraph (average) </li>
      <li><%= @ta.no_fluff_percentage %>% fluff free </li>
    </ul>
  </span>

app/views/poems/edit.html.erb
<% provide(:title, 'Edit Poem') %>
<h1>Edit Poem</h1>

<div class="row">
  <div class="span6  offset3">
    <%= render('form') %>
  </div>
</div>

app/views/poems/index.html.erb
<% provide(:title, @poet.name) %>
<h1>Poems by <%= @poet.name %></h1>
<div class="row">
  <div class="span12">
    <% if @poet.poems.any? %>
      <h3>Poems found (<%= @poet.poems.count %>)</h3>
      <%= paginate @poems %>  
      <ol class="poems">
        <%= render(@poems) %>
      </ol>
      <%= paginate @poems %>  
    <% end %> 
  </div>
</div>

app/views/poems/new.html.erb
<% provide(:title, 'New Poem') %>
<h1>New Poem</h1>
<div class="row">
  <div class="span6  offset3">
    <%= render('form') %>
  </div>
</div>

app/views/poems/show.html.erb
<% provide(:title,@poem.title ) %>
<h3><%= @poem.title %></h3> <br>
<div class="row .poems">
  <div class="span8">
    <span class="body"><%= simple_format(@poem.body) %></span>
    <span class="timestamp">
     Created by <%= @poem.user.name %>, <%= time_ago_in_words(@poem.created_at) %> ago. Likes (<%= pluralize(@poem.reputation_for(:votes).to_i, "vote") %>)
    </span>
    <% if current_user.id == @poem.user.id %>
     <span class="links">
      <%= link_to('My Poems', poems_path) %> |
      <%= link_to('Edit Poem', edit_poem_path(@poem)) %> |
      <%= link_to('Delete Poem', @poem,
                  method: :delete,
                  data: { confirm: "Are you sure?"},
                  title: @poem.title) %>
      </span>
    <% end %>
    <% if !current_user.voted_for?(@poem) && current_user %>
      <span class="links">
        Like the poem? <%= link_to("yes", vote_poem_path(@poem, type: "vote"), method: :post) %>
      </span>
    <% end %>
    <br><br>
    <button type="button" class="btn btn-primary btn-small" id="show_btn"
      data-toggle="button" >Show Analysis</button>
    <button type="button" class="btn btn-primary btn-small" id="hide_btn"
      data-toggle="button" >Hide Analysis</button>
    <span id="text"><%=  render('text_analyzer') %></span>
  </div>
</div>